# Generated by Django 3.0.3 on 2020-02-21 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comparison',
        ),
        migrations.DeleteModel(
            name='ComparisonItem',
        ),
    ]
